// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3x4U6-ldvVx2MbIy8iGD747CsUV2y-k',
    appId: '1:405568349036:web:d6b2b7bca010b30ac1c949',
    messagingSenderId: '405568349036',
    projectId: 'fahamugov-app',
    authDomain: 'fahamugov-app.firebaseapp.com',
    storageBucket: 'fahamugov-app.firebasestorage.app',
    measurementId: 'G-GGEPD807Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlrffMCPT6irhMi1raXVnavej5iCVtdNc',
    appId: '1:405568349036:android:db93cb988fabb54bc1c949',
    messagingSenderId: '405568349036',
    projectId: 'fahamugov-app',
    storageBucket: 'fahamugov-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpAwfJtxjpPF8gSk7HgaYJ9Tl3u0wY4M',
    appId: '1:405568349036:ios:58dc2213989aeb85c1c949',
    messagingSenderId: '405568349036',
    projectId: 'fahamugov-app',
    storageBucket: 'fahamugov-app.firebasestorage.app',
    iosBundleId: 'com.example.fahamuGov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHpAwfJtxjpPF8gSk7HgaYJ9Tl3u0wY4M',
    appId: '1:405568349036:ios:58dc2213989aeb85c1c949',
    messagingSenderId: '405568349036',
    projectId: 'fahamugov-app',
    storageBucket: 'fahamugov-app.firebasestorage.app',
    iosBundleId: 'com.example.fahamuGov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy3x4U6-ldvVx2MbIy8iGD747CsUV2y-k',
    appId: '1:405568349036:web:9ec3f2846b14f52dc1c949',
    messagingSenderId: '405568349036',
    projectId: 'fahamugov-app',
    authDomain: 'fahamugov-app.firebaseapp.com',
    storageBucket: 'fahamugov-app.firebasestorage.app',
    measurementId: 'G-P664R2YCHR',
  );
}
